### PR TITLE
Configure Exception Logging

### LINKED ISSUE #30: Rollbar Integration
When an error is generated in the system, it is important they are tracked so they can be properly triaged and resolved. Rollbar has proven to be extremely valuable for tracking errors.

Tasks:

- [x] Setup Rollbar
- [x] Document Configuration

### PR DESCRIPTION
**Pull request by samcdavid**
Why
---

- When an error is generated in the system, it is important they are
tracked so they can be properly triaged and resolved. Rollbar has proven
to be extremely valuable for tracking errors.

This change addresses the need by
---------------------------------

- Install `rollbax`
- Configure Rollbar reporting for production.
- Turn off Rollbar reporting in development and test by default.
- Update README

Related Issues
--------------

- Resolves #30

Next Steps
----------

- :shipit:

### CODE REVIEW

File: apps/web_delivery/config/config.exs [hunk 1]
```diff
@@ -18,6 +13,10 @@ config :logger, :console,
   format: "$time $metadata[$level] $message\n",
   metadata: [:request_id]
 
+config :rollbax,
+  access_token: System.get_env("ROLLBAR_ACCESS_TOKEN"),
+  environment: System.get_env("APPLICATION_ENVIRONMENT") || Mix.env
```
Comment (mjs2600) [inline apps/web_delivery/config/config.exs]: Why not `MIX_ENV` instead_of `APPLICATION_ENVIRONMENT`?

Comment (samcdavid) [inline apps/web_delivery/config/config.exs]: Because `MIX_ENV` would be `prod` instead of `production`. And the deploy notification hook for rollbar specifies `production` by default. It just keeps it more consistent with the other projects in rollbar. I'm happy to do whichever though.
